# Starter pipeline


trigger:
- master

pool:
  vmImage: 'Ubuntu 18.04'
  environment: nice-vm 


  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        sudo apt install mosquitto
        sudo cp ~/nice-mosquitto.conf /etc/mosquitto/conf.d
        sudo systemctl restart mosquitto.service
