# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureFileCopy@4
  inputs:
    SourcePath: 'https://raw.githubusercontent.com/sudipta-rudra/test/master/parameters.json'
    azureSubscription: 'niceatgserviceconnection'
    Destination: 'AzureBlob'
    storage: 'sardniceaccountname'
    ContainerName: 'local db'
    BlobPrefix: 'blob1'
