# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Azure service connection established during pipeline creation
  azureSubscription: dd7d79d6-5761-40bc-ae07-3a3df9a01302
  appName: Nice-web
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  appType: webAppLinux
  deploymentMethod: zipDeploy

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-nice - Azure'
    appType: 'webAppLinux'
    appName: 'azure-nice'
    deployToSlotOrASE: true
    resourceGroupName: 'sudipta-training-resource-group'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    
- task: AzureWebApp@1 # Add this at the end of your file
  inputs:
    azureSubscription: dd7d79d6-5761-40bc-ae07-3a3df9a01302
    appType: webAppLinux
    appName: $(Nice-web)
    package: $(System.ArtifactsDirectory)/**/*.zip
    
