trigger:
- master
- releases/*

pool:
  vmImage: 'ubuntu-18.04'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-nice - Azure'
    appType: 'webAppLinux'
    appName: 'azure-nice'
    deployToSlotOrASE: true
    resourceGroupName: 'sudipta-training-resource-group'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'

- task: AzureAppServiceSettings@1
  inputs:
    azureSubscription: 'azure-nice - Azure'
    appName: 'azure-nice'
    resourceGroupName: 'sudipta-training-resource-group'
    appSettings: |
      -Port 5000 -RequestTimeout 5000
      -WEBSITE_TIME_ZONE "Eastern Standard Time"
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-nice - Azure'
    appType: 'webAppLinux'
    appName: 'azure-nice'
    deployToSlotOrASE: true
    resourceGroupName: 'sudipta-training-resource-group'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'PYTHON|3.6'
    
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'azure-nice - Azure'
    appType: 'webAppLinux'
    WebAppName: 'azure-nice'
    deployToSlotOrASE: true
    ResourceGroupName: 'sudipta-training-resource-group'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'PYTHON|3.6'

  
- task: PublishBuildArtifacts@1
  
# variables:
#   # Azure service connection established during pipeline creation
#   azureSubscription: dd7d79d6-5761-40bc-ae07-3a3df9a01302
#   appName: Nice-web
#   # Agent VM image name
#   vmImageName: 'ubuntu-latest'
#   appType: 'webAppLinux'
#   deploymentMethod: 'zipDeploy'
