# Starter pipeline


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'devtestserviceconn'
    subscriptionId: 'dd7d79d6-5761-40bc-ae07-3a3df9a01302'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'vijay-training-resource-group'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'blob/master/template.json'
    csmParametersFileLink: 'blob/master/parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'az-servicebus'


