# Starter pipeline

steps:
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-nice - Azure'
    appType: 'webAppLinux'
    appName: 'azure-nice-ds'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'JAVA|8-jre8'

- task: AzureAppServiceSettings@1
  inputs:
    azureSubscription: 'azure-nice - Azure'
    appName: 'azure-nice-ds'
    connectionStrings: |
      ip ="52.176.146.3:1883"
      port = "4444"
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
