# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


jobs: 
- deployment: VMDeploy
  displayName: web
  environment:
    name: nice-vm
    resourceType: VirtualMachine
  strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Modify deployment script based on the app type
                echo "Starting deployment script run"
                sudo apt install mosquitto
                sudo cp ~/nice-mosquitto.conf /etc/mosquitto/conf.d
                sudo systemctl restart mosquitto.service
        
