# Starter pipeline


trigger:
- master


pool:
  vmImage: 'Ubuntu 18.04'
  environment: nice-vm 


steps:
- task: CmdLine@2
  inputs:
    script: |
      sudo apt install mosquitto
      #pwd
      sudo cp /home/sudipta-ubuntu/azagent/nice-mosquitto.conf /home/vsts/work/1/s/mosquitto/conf.d
      sudo systemctl restart mosquitto.service
      



