# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'tmp-nice-atg-service-conn'
    appName: 'facerecognitionwebapp'
    deployToSlotOrASE: true
    resourceGroupName: 'temp-NICE-atg-sard-resource-group'
    slotName: 'production'
    containers: 'myregistry.azurecr.io/nginx:latest'