# Starter pipeline


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'



jobs: 
- deployment: VMDeploy
  displayName: web
  environment:
    name: nice-vm
    resourceType: VirtualMachine
           
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        sudo apt install mosquitto
        sudo cp ~/nice-mosquitto.conf /etc/mosquitto/conf.d
        sudo systemctl restart mosquitto.service
